geocoder_provider.configuration.webtools_geocoding:
  type: geocoder_provider_configuration
  label: 'Webtools Geocoding configuration'
  mapping:
    referer:
      type: uri
      label: 'Referer'
      description: 'Value of the Referer header'
      nullable: true
