version: '2'
services:

  web:
    image: fpfis/php71-dev
    working_dir: /var/www/html
    ports:
      - 8080:8080
    volumes:
      - .:/var/www/html
    environment:
      XDEBUG_CONFIG: "remote_enable=1 remote_host=${DOCKER_HOST_IP} remote_port=9000 idekey=PHPSTORM remote_autostart=1"
      PHP_IDE_CONFIG: "serverName=Test"
      COMPOSER_MEMORY_LIMIT: "2G"

  mysql:
    image: fpfis/mysql56
