block.settings.oe_webtools_etrans:
  type: block_settings
  label: 'Webtools eTrans block'
  mapping:
    render_as:
      type: string
      label: 'Render as'
    render_to:
      type: string
      label: 'Render to'
