oe_webtools_page_feedback.settings:
  type: config_object
  label: 'Webtools Page Feedback Form settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enabled'
      description: 'Whether the Page Feedback Form is enabled or not.'
    embed_code:
      type: string
      label: 'Embed code'
      description: 'JSON-encoded Page Feedback Form configuration.'
