<?php

/**
 * @file
 * OpenEuropa Webtools cookie consent module.
 */

declare(strict_types = 1);

use Drupal\media\IFrameMarkup;

/**
 * Implements hook_preprocess_HOOK() for media-oembed-iframe.html.twig template.
 *
 * According to fact that from oEmbed service we receive html code with iframe,
 * we have to change "src" attribute value for cookie consent service usage.
 */
function oe_webtools_cookie_consent_preprocess_media_oembed_iframe(array &$variables): void {
  if ($variables['media'] instanceof IFrameMarkup) {
    preg_match('/<iframe.*src=["\']+([^"\']*)["\']+[^<>]*><\/iframe>/', $variables['media']->__toString(), $matches);
    if (!empty($matches[1])) {
      $new_iframe = str_replace($matches[1], '//ec.europa.eu/cookie-consent/iframe?oriurl=' . $matches[1] . '&lang=' . \Drupal::languageManager()->getCurrentLanguage()->getId(), $variables['media']);
      $variables['media'] = IFrameMarkup::create($new_iframe);
    }
  }
}
