<?php

/**
 * @file
 * OpenEuropa Webtools cookie consent module.
 */

declare(strict_types = 1);

use Drupal\Core\Cache\CacheableMetadata;
use Drupal\media\IFrameMarkup;
use Drupal\oe_webtools_cookie_consent\Event\CookieConsentEvent;

/**
 * Implements template_preprocess_media_oembed_iframe().
 *
 * Because the oEmbed format comes with the actual HTML iframe,
 * we have to change its "src" attribute value
 * with the URL of the Cookie Consent service, passing the original URL to it.
 */
function oe_webtools_cookie_consent_preprocess_media_oembed_iframe(array &$variables): void {
  if ($variables['media'] instanceof IFrameMarkup) {
    preg_match('/<iframe.*src=["\']+([^"\']*)["\']+[^<>]*><\/iframe>/', $variables['media']->__toString(), $matches);
    if (!empty($matches[1])) {
      $new_iframe = str_replace($matches[1], '//ec.europa.eu/cookie-consent/iframe?oriurl=' . $matches[1] . '&lang=' . \Drupal::languageManager()->getCurrentLanguage()->getId(), $variables['media']);
      $variables['media'] = IFrameMarkup::create($new_iframe);
    }
  }
}

/**
 * Implements hook_page_attachments().
 */
function oe_webtools_cookie_consent_page_attachments(array &$attachments) {
  $event = new CookieConsentEvent();
  $event_dispatcher = \Drupal::service('event_dispatcher');
  $event_dispatcher->dispatch(CookieConsentEvent::NAME, $event);

  $event_cache = CacheableMetadata::createFromObject($event);
  $existing_cache = CacheableMetadata::createFromRenderArray($attachments);

  $cache = $event_cache->merge($existing_cache);
  $cache->applyTo($attachments);

  if ($event->isCckEnabled()) {
    $attachments['#attached']['library'][] = 'oe_webtools_cookie_consent/drupal.webtools-cookie-consent';
  }
}
