<?php

/**
 * @file
 * Contains Drupal hooks.
 */

declare(strict_types = 1);

use Drupal\Core\Cache\CacheableMetadata;
use Drupal\oe_webtools_analytics\Event\AnalyticsEvent;

/**
 * Implements hook_page_attachments().
 *
 * Collects the Analytics settings and sets them as a JSON snippet.
 */
function oe_webtools_analytics_page_attachments(array &$attachments): void {
  $event = new AnalyticsEvent();
  $event_dispatcher = \Drupal::service('event_dispatcher');
  $event_dispatcher->dispatch(AnalyticsEvent::NAME, $event);

  $existing_cache = CacheableMetadata::createFromRenderArray($attachments);
  $event_cache = CacheableMetadata::createFromObject($event);

  if (!$event->isValid()) {
    $cache = $existing_cache->merge($event_cache);
    $cache->applyTo($attachments);
    return;
  }

  $analytics_attachment = [
    '#type' => 'html_tag',
    '#tag' => 'script',
    '#value' => $event,
    '#attributes' => ['type' => 'application/json'],
  ];

  $event_cache->applyTo($attachments);
  $attachments['#attached']['html_head'][] = [
    $analytics_attachment,
    // A key, to make it possible to recognize this when altering.
    'oe_webtools_analytics',
  ];
  $attachments['#attached']['library'][] = 'oe_webtools/drupal.webtools-smartloader';
}
