<?php

/**
 * @file
 * Contains Drupal hooks.
 */

declare(strict_types = 1);

use Drupal\oe_webtools_analytics\Event\AnalyticsEvent;
use Drupal\Core\Cache\CacheableMetadata;

/**
 * Implements hook_page_attachments().
 *
 * Collects the Analytics settings and sets them as a JSON snippet.
 */
function oe_webtools_analytics_page_attachments(array &$attachments) {
  $import_settings_event = new AnalyticsEvent();
  $event_dispatcher = \Drupal::service('event_dispatcher');
  $event_dispatcher->dispatch(AnalyticsEvent::NAME, $import_settings_event);

  if (!$import_settings_event->isValid()) {
    return;
  }

  $analytics_attachment = [
    '#type' => 'html_tag',
    '#tag' => 'script',
    '#value' => $import_settings_event,
    '#attributes' => ['type' => 'application/json'],
  ];

  $cache = CacheableMetadata::createFromObject($import_settings_event);
  $cache->applyTo($analytics_attachment);
  $attachments['#attached']['html_head'][] = [
    $analytics_attachment,
    // A key, to make it possible to recognize this when altering.
    'oe_webtools_analytics',
  ];
}
