<?php

/**
 * @file
 * Contains Drupal hooks.
 */

declare(strict_types=1);

use Drupal\Core\Cache\CacheableMetadata;
use Drupal\oe_webtools_analytics\Event\AnalyticsEvent;

/**
 * Implements hook_page_bottom().
 */
function oe_webtools_analytics_page_bottom(array &$page_bottom) {
  $event = new AnalyticsEvent();
  $event_dispatcher = \Drupal::service('event_dispatcher');
  $event_dispatcher->dispatch($event, AnalyticsEvent::NAME);

  $existing_cache = CacheableMetadata::createFromRenderArray($page_bottom);
  $event_cache = CacheableMetadata::createFromObject($event);

  $cache = $existing_cache->merge($event_cache);
  $cache->applyTo($page_bottom);

  if (!$event->isValid()) {
    return;
  }

  $page_bottom['oe_webtools_analytics'][] = [
    '#type' => 'html_tag',
    '#tag' => 'script',
    '#value' => $event,
    '#attributes' => ['type' => 'application/json'],
  ];
  $page_bottom['#attached']['library'][] = 'oe_webtools/drupal.webtools-smartloader';
}
