oe_webtools_html2media.settings:
  type: config_object
  label: 'Webtools HTML2Media settings'
  mapping:
    url:
      type: label
      label: 'Webtols html2media webservice url'
      description: 'A URL that will be called on request.'
