<?php

/**
 * @file
 * OpenEuropa Webtools Hotjar module.
 */

declare(strict_types=1);

use Drupal\Component\Serialization\Json;
use Drupal\Core\Cache\CacheableMetadata;

/**
 * Implements hook_page_bottom().
 */
function oe_webtools_hotjar_page_bottom(array &$page_bottom) {
  $cache = CacheableMetadata::createFromRenderArray($page_bottom);
  $cache->addCacheContexts(['user.roles:anonymous']);

  $config = \Drupal::config('oe_webtools_hotjar.settings');
  $enabled = (bool) $config->get('enabled');
  $site = $config->get('site');
  $cache->addCacheableDependency($config);
  $cache->applyTo($page_bottom);
  if (\Drupal::currentUser()->isAnonymous() && $enabled && $site != "") {
    $page_bottom['#attached']['library'][] = 'oe_webtools/drupal.webtools-smartloader';
    $script_values = [
      'utility' => 'hotjar',
      'site' => $site,
    ];

    $page_bottom['oe_webtools_hotjar'][] = [
      '#type' => 'html_tag',
      '#tag' => 'script',
      '#value' => Json::encode($script_values),
      '#attributes' => ['type' => 'application/json'],
    ];
  }

}
