<?php

/**
 * @file
 * OpenEuropa Webtools Laco Widget module.
 */

declare(strict_types=1);

use Drupal\Core\Cache\CacheableMetadata;

/**
 * Implements hook_page_bottom().
 */
function oe_webtools_laco_widget_page_bottom(array &$page_bottom) {
  $logger = \Drupal::logger('oe_webtools_laco_widget');
  $config = \Drupal::config('oe_webtools_laco_widget.settings');

  // Do not add LACO widget related JSON if it is disabled in the config.
  if (!$config->get('enabled')) {
    return;
  }

  $include = $config->get('include');
  if (!$include) {
    $logger->warning('There are no selectors to include the Laco widget for.
    Please either provide include selectors or uninstall the module.');
    return;
  }

  $json = [
    'service' => 'laco',
    'include' => implode(', ', $include),
    'coverage' => [
      'document' => $config->get('coverage.document'),
      'page' => $config->get('coverage.page'),
    ],
    'icon' => $config->get('icon'),
  ];

  $exclude = $config->get('exclude');
  if ($exclude) {
    $json['exclude'] = implode(', ', $exclude);
  }

  $ignore = $config->get('ignore');
  if ($ignore) {
    $json['ignore'] = $ignore;
  }

  $page_bottom['oe_webtools_cookie_consent'][] = [
    '#type' => 'html_tag',
    '#tag' => 'script',
    '#value' => json_encode($json),
    '#attributes' => ['type' => 'application/json'],
  ];

  $page_bottom['#attached']['library'][] = 'oe_webtools/drupal.webtools-smartloader';
  $cache = CacheableMetadata::createFromRenderArray($page_bottom);
  $cache->addCacheableDependency($config);
  $cache->applyTo($page_bottom);
}
