<?php

/**
 * @file
 * Contains Drupal hooks.
 */

declare(strict_types = 1);

use Drupal\Core\Asset\AttachedAssetsInterface;
use Drupal\Core\Cache\CacheableMetadata;

/**
 * Implements hook_page_attachments().
 *
 * Attach smart loader.
 */
function oe_webtools_globan_page_attachments(array &$attachments): void {
  if (\Drupal::service('router.admin_context')->isAdminRoute()) {
    return;
  }

  /** @var \Drupal\Core\Config\ConfigFactoryInterface $config */
  $config = \Drupal::service('config.factory')->getEditable('oe_webtools_globan.settings');

  $existing_cache = CacheableMetadata::createFromRenderArray($attachments);
  $config_cache = CacheableMetadata::createFromObject($config);
  $cache = $existing_cache->merge($config_cache);
  $cache->applyTo($attachments);
  $attachments['#attached']['library'][] = 'oe_webtools/drupal.webtools-smartloader';
}

/**
 * Implements hook_js_alter().
 */
function oe_webtools_globan_js_alter(&$javascript, AttachedAssetsInterface $assets) {
  if (!\Drupal::service('router.admin_context')->isAdminRoute() && isset($javascript['//europa.eu/webtools/load.js'])) {
    /** @var \Drupal\Core\Config\ConfigFactoryInterface $config */
    $config = \Drupal::service('config.factory')->getEditable('oe_webtools_globan.settings');

    $globan_param = $config->get('display_eu_flag') ?? '1';
    $globan_param .= $config->get('background_theme') ?? '1';
    $globan_param .= $config->get('eu_institutions_links') ?? '1';

    $lang = '';
    if ($config->get('override_page_lang')) {
      $lang = '&lang=' . $config->get('override_page_lang');
    }

    $javascript['//europa.eu/webtools/load.js']['data'] .= '?globan=' . $globan_param . $lang;
  }
}
