<?php

/**
 * @file
 * The Webtools Global Banner module file.
 */

declare(strict_types = 1);

use Drupal\Component\Utility\UrlHelper;
use Drupal\Core\Asset\AttachedAssetsInterface;
use Drupal\Core\Cache\CacheableMetadata;
use Drupal\Core\Url;

/**
 * Implements hook_page_attachments().
 *
 * Attach smart loader.
 */
function oe_webtools_globan_page_attachments(array &$attachments): void {
  if (\Drupal::service('router.admin_context')->isAdminRoute()) {
    return;
  }

  /** @var \Drupal\Core\Config\ConfigFactoryInterface $config */
  $config = \Drupal::service('config.factory')->get('oe_webtools_globan.settings');

  $existing_cache = CacheableMetadata::createFromRenderArray($attachments);
  $config_cache = CacheableMetadata::createFromObject($config);
  $cache = $existing_cache->merge($config_cache);
  $cache->applyTo($attachments);
  $attachments['#attached']['library'][] = 'oe_webtools/drupal.webtools-smartloader';
}

/**
 * Implements hook_js_alter().
 */
function oe_webtools_globan_js_alter(&$javascript, AttachedAssetsInterface $assets) {
  if (!\Drupal::service('router.admin_context')->isAdminRoute() && isset($javascript['//europa.eu/webtools/load.js'])) {
    $new_url = UrlHelper::parse($javascript['//europa.eu/webtools/load.js']['data']);

    /** @var \Drupal\Core\Config\ConfigFactoryInterface $config */
    $config = \Drupal::service('config.factory')->get('oe_webtools_globan.settings');

    $globan_param = empty($config->get('display_eu_flag')) ? '0' : '1';

    switch ($config->get('background_theme')) {
      case 'light':
        $globan_param .= '0';
        break;

      case 'dark':
        $globan_param .= '1';
        break;

      default:
        $globan_param .= '1';
    }

    $globan_param .= empty($config->get('display_eu_institutions_links')) ? '0' : '1';

    $new_url['query']['globan'] = $globan_param;

    if ($config->get('override_page_lang')) {
      $new_url['query']['lang'] = $config->get('override_page_lang');
    }

    $javascript['//europa.eu/webtools/load.js']['data'] = Url::fromUri($new_url['path'], ['query' => $new_url['query']])->toString();
  }
}
